
export const SET_MAIN_TITLE = 'SET_MAIN_TITLE'
export const SET_TITLE = 'SET_TITLE'
export const SET_DESCIPTION = 'SET_DESCIPTION'
export const ADD_QUESTION = 'ADD_QUESTION'
export const EDIT_QUESTION = 'EDIT_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const ADD_DUPLICATE_QUESTION = 'ADD_DUPLICATE_QUESTION'